### ISSUE TITLE
Non-square avatars get stretched in the navbar

### ISSUE THREAD

**Issue by juliekoubova** [ramaboo/burn#12]
If the avatar picture isn't square, it will get stretched in the navbar.

![image](https://user-images.githubusercontent.com/142506/154949836-42f43e6e-7792-431c-a363-7f6b62b54c4c.png)

https://github.com/ramaboo/burn/blob/a47b00136e997915b65c6097779b7dc51c35e863/app/views/shared/navbar/_user.html.slim#L4

**Comment by ramaboo** [comment]
This should be fixed now. Let me know if you still experience it after uploading a new photo.
